- name: (2025) SC25 student volunteer
- name: (2023-Present) PURA salary award reviewer
- name: (2023-24) CSE Graduate Student Association vice-president
- name: (2022-23) CSE Graduate Student Association events chair

